FROM --platform=$BUILDPLATFORM registry.suse.com/bci/bci-base:15.7 AS build

RUN zypper in -y wget git

# All downloaded binaries are used at the build layer only,
# therefore they can be based off the BUILD PLATFORM architecture.
ARG BUILDARCH

ARG VERSION
ENV CHART_VERSION=${VERSION}

# set up helm 3
ENV HELM_VERSION=v4.1.3-bgtest
RUN wget https://github.com/bhartigautam156/helm/releases/download/${HELM_VERSION}/helm-${HELM_VERSION}-linux-${BUILDARCH}.tar.gz -O - | \
    tar -xz --strip-components=1 -C /usr/bin && \
    mv /usr/bin/helm /usr/bin/helm_v4 && \
    chown root:root /usr/bin/helm_v4 && \
    chmod +x /usr/bin/helm_v4

ENV YQ_VERSION=v4.44.2
RUN wget -q https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${BUILDARCH}.tar.gz -O - | \
        tar xz && mv yq_linux_${BUILDARCH} /usr/bin/yq

WORKDIR /src
COPY .git/ /src/.git/
COPY chart/ /src/chart/
COPY scripts/ /src/scripts/
COPY build.yaml .

RUN /src/scripts/export-config
RUN /src/scripts/chart/ci

FROM scratch
COPY --from=build /usr/bin/helm_v4 /helm
COPY --from=build /src/bin/chart/*/*.tgz /
COPY package/installer-run.sh /run.sh
